theme: jekyll-theme-minimal
color-scheme: auto
title: Raini Helmstadter's Earth Data Analytics Portfoli
# logo: /img/<Profile_Photo.jpg>
github_is_project_page: false

  
description: I'll be continuously updating this page throughout the Earth Data Analytics certificate program!
